config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "contact" => "pages#contact"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :tasks

  resources :teams, only: %i[new create show] do
    resources :rewards, except: %i[show]
    get "wheel", to: "teams#run_wheel"

    resources :rewards, except: %i[show] do
      member do
        get :select
      end
    end
  end

  resources :memories

  resources :chatrooms, only: %i[new create show] do
    resources :messages, only: :create
  end

  resources :users, only: :show do
    resources :lists
  end
end

app/models/task.rb
class Task < ApplicationRecord
  CATEGORIES = ["Tu crains dégun mais tu dois en prendre soin...",
                "La maison elle va pas se gérer seule, figure de poulpe !",
                "Fais tes papiers avant que ce soit le oaï !"]

  PRIORITY = ["Tranquille",
              "Passe la seconde !",
              "Ça urge fada !"]

  belongs_to :user
  has_many :task_managers, dependent: :destroy
  has_many :users, through: :task_managers
  belongs_to :team, optional: true

  validates :name, :category, :points, :deadline, presence: true
  validates :points, numericality: { only_integer: true }
  validates :name, length: { maximum: 100 }
  validates :category, inclusion: { in: CATEGORIES }
  # validates :reccurence, inclusion: { in: [true, false] }
  # validates :achieved, inclusion: { in: [true, false] }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: %i[show edit update destroy]

  def index

    @my_tasks_ids = current_user.task_managers.map { |tm| tm.task_id }
    @tasks = Task.where(id: @my_tasks_ids)


    if params[:filter] && params[:filter][:date].present?
      selected_date = Date.parse(params[:filter][:date])
      @tasks = @tasks.where(deadline: selected_date)
    end

    respond_to do |format|
      format.html do
        if request.xhr?
          render partial: "tasks/tasks_list", locals: { tasks: @tasks }, layout: false
        end
      end
      format.text do
        if request.xhr?
          render partial: "tasks/tasks_list", locals: { tasks: @tasks }, layout: false
        end
      end
    end
  end


  def show
  end

  def new
    @task = Task.new
    @task.user = current_user
    @members = @task.user.team.users
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    if @task.save
      member_ids = params[:task][:members]
      if params[:task][:reccurence] == "0"
        ids = member_ids.map { |member| member[:user_id] }
        ids.each do |id|
          user = User.find(id)
          user.task_managers << TaskManager.create(task: @task, user: user)
        end
      else
        @task.save
      end
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    was_achieved = @task.achieved
    @task.update(task_params)
    @team = current_user.team
    @reward = @team.rewards.find { |reward| reward.selected == true }

    if @task.achieved == true && was_achieved == false
      @team.update(score: @team.score += @task.points)
      if @team.score >= @reward.goal
        redirect_to user_path(current_user)
        flash[:notice] = "Bravo ! #{@team.name} a remporté : #{@reward.name}"
      else
        redirect_to user_path(current_user)
      end
    else
      redirect_to user_path(current_user)
    end
    # redirect_back fallback_location: root_path, notice: "Task updated"
  end

  def destroy
    @task.destroy
    redirect_to user_path(current_user)
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :category, :reccurence, :points, :deadline, :achieved, :priority)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/views/tasks/_tasks_list.html.erb
<!-- app/views/tasks/_tasks_list.html.erb -->


<% if tasks.empty? %>
  <h3 class="card-empty mb-4">Tié en détente aujourd'hui !</h3>
<% else %>
  <% tasks.each do |task| %>
    <% if task.category == Task::CATEGORIES[0] %>  <!-- CATEGORIES[0] = "Santé" -->
      <%= link_to edit_task_path(task), class: "card card-task card-health mb-4", data: { aos: "flip-up" } do %>
        <div class="card-content">
          <h3><%= task.name %></h3>
          <p><%= task.description %></p>
        </div>
        <div class="card-checkboxe">
          <% if task.achieved %>
            <%= image_tag "checkboxe-checked.svg" %>
          <% else %>
            <%= image_tag "checkboxe.svg" %>
          <% end %>
        </div>
      <% end %>
    <% elsif task.category == Task::CATEGORIES[1] %>  <!-- CATEGORIES[1] = "Gestion du foyer" -->
      <%= link_to edit_task_path(task), class: "card card-task card-home-duty mb-4", data: { aos: "flip-up" } do %>
        <div class="card-content">
          <h3><%= task.name %></h3>
          <p><%= task.description %></p>
        </div>
        <div class="card-checkboxe">
          <% if task.achieved %>
            <%= image_tag "checkboxe-checked.svg" %>
          <% else %>
            <%= image_tag "checkboxe.svg" %>
          <% end %>
        </div>
      <% end %>
    <% elsif task.category == Task::CATEGORIES[2] %>  <!-- CATEGORIES[2] = "Administratif" -->
      <%= link_to edit_task_path(task), class: "card card-task card-admin mb-4", data: { aos: "flip-up" } do %>
        <div class="card-content">
          <h3><%= task.name %></h3>
          <p><%= task.description %></p>
        </div>
        <div class="card-checkboxe">
          <% if task.achieved %>
            <%= image_tag "checkboxe-checked.svg" %>
          <% else %>
            <%= image_tag "checkboxe.svg" %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
            <div class="row justify-content-center">
              <div class="col-md-12">
                <div class="form-container">
                  <div class="container-header text-center">
                    <h1>Modifier la tâche</h1>
                  </div>
                  <div class="card form-input">
                    <%= simple_form_for @task, data: {turbo_stream: false} do |f| %>
                        <%= f.input :name, label: "Nom", input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
                        <%= f.input :description, label: "Détails", input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
                        <%= f.input :category,
                          label: "Catégorie",
                          as: :radio_buttons,
                          collection_wrapper_tag: 'div',
                          collection_wrapper_class: 'category-wrapper',
                          item_wrapper_class: 'category-item',
                          input_html: {class: 'category-selector'},
                          collection: Task::CATEGORIES,
                          label_html: { class: 'form-label' } %>

                        <%= f.input :reccurence, label: "Réccurente", as: :boolean, input_html: { class: 'form-check-input' }, label_html: { class: 'form-check-label' } %>

                        <%= f.input :points, label: "Points", input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>

                        <%= f.input :achieved, label: "Tache achevée", as: :boolean, input_html: { class: 'form-check-input toggle' }, label_html: { class: 'form-check-label' } %>

                        <%= f.input :deadline,
                                    label: "Deadline",
                                    as: :string,
                                    input_html: { data: { controller: "datepicker" }, class: 'form-control' },
                                    label_html: { class: 'form-label' } %>
                        <%= f.input :priority,
                          label: "Priorité",
                          as: :radio_buttons,
                          collection_wrapper_tag: 'div',
                          collection_wrapper_class: 'd-flex flex-wrap',
                          input_html: { class: "tag-selector" },
                          item_wrapper_class: 'tag-item  mb-3',
                          collection: Task::PRIORITY,
                          label_html: { class: 'form-label' } %>

                    <div class="form-actions text-center my-4">
                      <%= f.button :submit, 'Enregitrer', class: 'btn btn-orange mx-2 my-2' %>
                      <%= link_to 'Supprimer', task_path(@task), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-delete mx-2 my-2" %>
                    </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>

app/views/tasks/index.html.erb
<div class="container" data-controller="tasks">
  <h1 class="mb-3">Tâches à venir</h1>

  <%= simple_form_for :filter, url: tasks_path, method: :get do |f| %>
    <div class="calendar mb-4">
      <% (Date.today - 2..Date.today + 2).each do |date| %>
        <div class="tag-item">
          <%= f.radio_button :date, date, id: "date_#{date}", class: "tag-selector visually-hidden", data: { action: "tasks#filterTasks", tasks_target: "date" } %>
          <%= f.label :date, for: "date_#{date}", class: "tag-date text-center" do %>
            <%= content_tag :span, date.strftime('%a'), class: "d-block text-center" %>
            <%= content_tag :span, date.strftime('%e'), class: "d-block text-center tag-day" %>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= f.submit "Filter Tasks", class: "btn btn-primary", style: "display:none;" %>
  <% end %>

  <div id="tasks-list">
    <%= render partial: "tasks/tasks_list", locals: { tasks: @tasks }, layout: false %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
    <div class="row justify-content-center">
      <div class="col">
        <div class="form-container">
          <div class="container-header text-center">
            <h1>Nouvelle tâche</h1>
          </div>
          <div class="card form-input">
            <%= simple_form_for @task do |f| %>
              <div class="form-group">
                <%= f.input :name, label: "Nom", input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
              </div>
              <div class="form-group">
                <%= f.input :description, label: "Détails", input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
              </div>

              <%= f.input :category,
                  label: "Catégorie",
                  as: :radio_buttons,
                  collection_wrapper_tag: 'div',
                  collection_wrapper_class: 'category-wrapper',
                  item_wrapper_class: 'category-item',
                  input_html: {class: 'category-selector'},
                  collection: Task::CATEGORIES,
                  label_html: { class: 'form-label' } %>

              <div class="form-group">
                <%= f.input :reccurence, label: "Réccurente", as: :boolean, input_html: { class: 'form-check-input' }, label_html: { class: 'form-check-label' } %>
              </div>
              <div class="form-group">
                <%= f.input :points, label: "Points", input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
              </div>

              <p class="form-label">Qui doit réaliser cette tâche ?</p>
                <div class="d-flex flex-wrap" data-controller="member-selection">
                  <% @members.each do |member| %>
                    <div>
                      <%= check_box_tag 'task[members][]', member.id, false, id: "member_#{member.id}", class: 'form-check-input', style: 'display:none;', data: { member_selection_target: "checkbox" } %>
                      <div class="member-photo-container">
                        <div class="member-photo" data-member-selection-target="photo" data-member-id="<%= member.id %>" onclick="document.getElementById('member_<%= member.id %>').click()">
                          <%= image_tag(member.avatar, alt: member.first_name, style: "width:50px; cursor: pointer;") %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
                <%= f.input :deadline,
                            :label => "Deadline",
                            as: :string,
                            input_html: { data: { controller: "datepicker" }, class: 'form-control' },
                            label_html: { class: 'form-label' } %>

             <div class="form-group">
                <%= f.input :priority,
                  label: "Priorité",
                  as: :check_boxes,
                  collection_wrapper_tag: 'div',
                  collection_wrapper_class: 'd-flex flex-wrap justify-content-center',
                  input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item  mb-3',
                  collection: Task::PRIORITY,
                  label_html: { class: 'form-label' } %>

              </div>
            <div class="form-actions text-center mt-5 my-4">
                <%= f.submit 'Ajoute la', class: 'btn btn-orange' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/tasks/show.html.erb
<div>
  <h1>
    <%= @task.name %>
  </h1>
</div>

<%= link_to 'Delete', task_path(@task), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>