config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "contact" => "pages#contact"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :tasks

  resources :teams, only: %i[new create show] do
    resources :rewards, except: %i[show]
    get "wheel", to: "teams#run_wheel"

    resources :rewards, except: %i[show] do
      member do
        get :select
      end
    end
  end

  resources :memories

  resources :chatrooms, only: %i[new create show] do
    resources :messages, only: :create
  end

  resources :users, only: :show do
    resources :lists
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :team
  belongs_to :user

  validates :name, presence: true
  validates :goal, numericality: { greater_than_or_equal_to: 0, only_integer: true }
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  # def index
  #   # @team = Team.find(params[:team_id])
  #   # @rewards = @team.rewards

  # end

  before_action :set_team

  def index
    @rewards = @team.rewards
    @selected_reward = @team.rewards.find_by(selected: true)
  end

  def select
    @reward = @team.rewards.find(params[:id])
    @team.rewards.update_all(selected: false)
    @reward.update(selected: true)
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'La récompense a été choisie.' }
      format.json { render json: { success: true, reward_id: @reward.id } }
    end
  end

  def new
    @team = Team.find(params[:team_id])
    @reward = Reward.new
  end

  def create
    @team = Team.find(params[:team_id])
    @reward = Reward.new(reward_params)
    @reward.team_id = current_user.team_id
    @reward.user_id = current_user.id

    if @reward.save
      redirect_to team_rewards_path(@team), notice: 'La recompense est créée.'
    else
      render :new
    end
  end

  def edit
    @team = Team.find(params[:team_id])
    @reward = @team.rewards.find(params[:id])
  end

  def update
    @team = Team.find(params[:team_id])
    @reward = @team.rewards.find(params[:id])
    if @reward.update(reward_params)
      redirect_to team_rewards_path(@team, @reward), notice: 'La recompense est mise à jour.'
    else
      render :edit
    end
  end

  def destroy
    @team = Team.find(params[:team_id])
    @reward = @team.rewards.find(params[:id])
    @reward.destroy
    redirect_to team_rewards_path(@team), status: :see_other
  end

  private

  def reward_params
    params.require(:reward).permit(:name, :goal)
  end

  def set_team
    @team = Team.find(params[:team_id])
  end
end

app/views/rewards/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="form-container">
        <div class="container-header text-center">
          <h1>Modifier la récompense</h1>
        </div>
        <div class="card form-input">
          <%= simple_form_for [@team, @reward], html: { class: 'form' } do |f| %>
            <div class="form-inputs mb-5">
              <%= f.input :name, label: "Nom de la récompense" %>
              <%= f.input :goal, label: "Objectif" %>
            </div>

            <div class="form-actions text-center my-4">
              <%= f.button :submit, 'Modifier', class: 'btn btn-orange' %>
              <%= link_to 'Supprimer', team_reward_path(@team, @reward), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-reward' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/rewards/index.html.erb
<div class="container text-center pt-4">
  <h1>Pour quelle récompense tu veux jouer ?</h1>

  <div class="row">
    <% @rewards.each do |reward| %>
      <div class="col-md-4 mb-4">
        <%= link_to team_path(@team), class: 'text-decoration-none' do %>
          <div class="card h-100 card-reward">
            <div class="card-body">
              <div class="row mb-3">
                <div class="col">
                  <h3 class="text-dark"><%= reward.name %></h3>
                </div>
              </div>
              <div class="row mb-3">
                <div class="col">
                  <p class="text-dark">Objectif: <strong><%= reward.goal %></strong></p>
                </div>
              </div>
                <div class="row justify-content-center">
                  <div class="col text-center">
                    <%= link_to 'Modifier', edit_team_reward_path(@team, reward), class: 'btn btn-orange m-1' %>
                    <%= link_to 'Sélectionner', select_team_reward_path(@team, reward), class: 'btn btn-reward m-1' %>
                 </div>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    <% end %>

    <div>
      <%= link_to 'Nouvelle Récompense', new_team_reward_path(@team), class: 'btn btn-yellow' %>
    </div>
  </div>
  </div>

app/views/rewards/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col">
      <div class="form-container">
        <div class="container-header text-center">
          <h1>Nouvelle récompense</h1>
        </div>

        <div class="card form-input">
          <%= simple_form_for [@team, @reward], html: { class: 'form' } do |f| %>
            <div class="form-inputs">
              <%= f.input :name, label: "Nom de la récompense" %>
              <%= f.input :goal, label: "Objectif" %>
            </div>

            <div class="form-actions text-center my-4">
              <%= f.button :submit, 'Ajoute la', class: 'btn btn-orange' %>
            </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>