config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "contact" => "pages#contact"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :tasks

  resources :teams, only: %i[new create show] do
    resources :rewards, except: %i[show]
    get "wheel", to: "teams#run_wheel"

    resources :rewards, except: %i[show] do
      member do
        get :select
      end
    end
  end

  resources :memories

  resources :chatrooms, only: %i[new create show] do
    resources :messages, only: :create
  end

  resources :users, only: :show do
    resources :lists
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_memorie, only: %i[show edit update destroy]

  def index
    @memories = Memorie.all
  end

  def show
  end

  def new
    @memorie = Memorie.new
  end

  def create
    @memorie = Memorie.new(memorie_params)
    @memorie.team_id = current_user.team_id
    if @memorie.save
      redirect_to memory_path(@memorie)
    else
      puts @memorie.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @memorie = Memorie.find(params[:id])
    if @memorie.update(memorie_params)
      redirect_to @memorie
    else
      render :edit
    end
  end

  def destroy
    @memorie = Memorie.find(params[:id])
    @memorie.destroy
    redirect_to memories_path
  end

  private

  def memorie_params
    params.require(:memorie).permit(:name, :content, :date, :photo)
  end

  def set_memorie
    @memorie = Memorie.find(params[:id])
  end
end

app/views/memories/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="form-container">
        <div class="container-header text-center">
          <h1>Modifier le Souvenir</h1>
        </div>
        <div class="card form-input">
          <%= simple_form_for @memorie do |f| %>
            <div class="form-inputs mb-5">
              <%= f.input :name, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
              <%= f.input :content, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
              <%= f.input :date, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
              <%= f.input :photo, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
              <%= f.button :submit, "modifier", class: 'btn btn-orange' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/memories/index.html.erb
<div class="container mmy-1">
    <h1 class="text-center">Les Souvenirs</h1>
    <br>
    <div class="form-container">
    <div class="row">
      <% @memories.each do |memorie| %>
        <div class="col-md-4 mb-4">

            <div class="card w-100 h-100 card-memorie">
              <div class="card-body">
                  <h4 class="card-title text-center"><%= link_to memorie.name, memory_path(memorie), class: 'text-decoration-none' %></h4>
                  <h5 class="card-title text-center"><%= link_to memorie.date, memory_path(memorie), class: 'text-decoration-none' %></h5>
                  <p class="card-title text-center">"<%= link_to memorie.content, memory_path(memorie), class: 'text-decoration-none' %>..."</p>
              </div>
                  <div class="mt-auto d-flex justify-content-center" style="margin-bottom: 10px">

                  </div>
            </div>

        </div>
      <% end %>
    <div class="d-flex justify-content-center my-3">
    <%= link_to "ajouter un souvenir", new_memory_path, class: "btn btn-yellow" %>
    </div>
    </div>
    </div>
  </div>

app/views/memories/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col">
      <div class="form-container">
        <div class="container-header text-center">
          <h1>New Memory</h1>
        </div>
        <div class="card form-input">
          <%= simple_form_for @memorie do |f| %>
            <div class="form-inputs mb-5">
              <%= f.input :name, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
              <%= f.input :content, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
              <%= f.input :date, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
              <%= f.input :photo, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
              <%= link_to "retour", memories_path(@memorie), class: "btn mx-2" %>
              <%= f.button :submit, "créer", class: 'btn btn-purple' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/memories/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<div class="container mt-5">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2">
      <div class="form-container">
        <div class="card-body">
          <div class="text-center mb-3">
            <h5>Le "<%= @memorie.date %>"</h5>
          </div>
          <h1 class="card-title text-center mb-3"><%= @memorie.name %></h1>
          <div class="text-center mb-3">
            <p>"<%= @memorie.content %>..."</p>
          </div>
          <div class="card">
            <% if @memorie.photo.present? %>
            <div class="text-center mb-4">
              <%= image_tag @memorie.photo, class: 'img-fluid', alt: 'Memory Photo' %>
            </div>
            <% end %>
            <hr>
            <div class="d-flex justify-content-center flex-wrap">
              <%= link_to "modifier", edit_memory_path, class: "btn btn-pink mx-2 mb-2" %>
              <%= link_to "Supprimer", memory_path(@memorie), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-orange mx-2 mb-2' %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>