config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "contact" => "pages#contact"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :tasks

  resources :teams, only: %i[new create show] do
    resources :rewards, except: %i[show]
    get "wheel", to: "teams#run_wheel"

    resources :rewards, except: %i[show] do
      member do
        get :select
      end
    end
  end

  resources :memories

  resources :chatrooms, only: %i[new create show] do
    resources :messages, only: :create
  end

  resources :users, only: :show do
    resources :lists
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">

  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>

  <div>
    <p>© 2024 La Tcheam. Tous droits réservés.</p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
  <div class="navbar navbar-expand-md navbar-light navbar-lewagon">
    <div class="container container-fluid" data-controller="navbar">
      <a class="navbar-brand" href="/">
        <%= image_tag ("ma-tcheam-logo-pink.svg") %>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" data-action="click->navbar#toggle">
        <%= image_tag ("burger-menu.svg"), data: { navbar_target:"menu"} %>
        <%= image_tag ("close-button.svg"), data: { navbar_target:"close"}, class:"d-none" %>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <% if (current_user) %>
          <ul class="navbar-nav me-auto menu-main">
            <li class="nav-item">
              <%= link_to "Ma tcheam", team_path(current_user.team), class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "La cascade des tâches ", team_wheel_path(current_user.team), class:"nav-link", data: { turbo: false } %>
            </li>
            <li class="nav-item">
              <%= link_to "+ Tâche", new_task_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "+ Liste", new_user_list_path(current_user), class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "+ Récompense", new_team_reward_path(current_user.team), class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Nos souvenirs", memories_path, class:"nav-link" %>
            </li>
          </ul>

            <ul class="navbar-nav me-auto menu-profile">
              <li class="nav-item dropdown">
                <%= image_tag current_user.avatar, class: "avatar dropdown-toggle avatar-bordered", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } %>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to 'Profile', edit_user_registration_path, class:"dropdown-item"  %>
                  <%= link_to 'Deconnexion', destroy_user_session_path, data: { turbo_method: :delete }, class:"dropdown-item" %>
                </div>
              </li>
              <!--li class="nav-item"-->
              <!--/li-->
          </ul>
        <% end %>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ma Tcheam - gère ta charge mentale comme un jeu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="csrf_token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
    <%= javascript_importmap_tags %>
    <meta property="og:" content="Matcheam - Gestion Familiale Amusante" />
    <meta property="og:description" content="Matcheam transforme la gestion des tâches familiales en une expérience amusante et collaborative, renforçant les liens familiaux avec un système de points et de récompenses." />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.ma-team.xyz" />
    <meta property="og:image" content="https://www.ma-team.xyz/avatar-poulpe.jpg" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'chatrooms/chatroombutton' %>
  </body>

  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
  <script>
    AOS.init();
  </script>
</html>